name: Mentorship Automation

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'create-project'
        type: choice
        options:
          - create-project
          - migrate-pairings
          - generate-folders
          - sync-projects
      project_title:
        description: 'Project title (for create-project)'
        required: false
        default: 'Mentorship 2025'
      pairings_path:
        description: 'Path to pairings folder (for migration)'
        required: false
        default: 'pairings'
      pair_data_file:
        description: 'JSON file with pair data'
        required: false

  schedule:
    # Run weekly sync on Sundays at 12:00 UTC
    - cron: '0 12 * * 0'

  issues:
    types: [opened, edited]

jobs:
  mentorship-automation:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Set up environment
      run: |
        chmod +x scripts/manage_mentorship_projects.py
        chmod +x scripts/migrate_pairings_to_projects.py

    - name: Run Mentorship Script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Personal Access Token with 'repo' and 'projects' scopes
        ACTION: ${{ github.event.inputs.action }}
        PROJECT_TITLE: ${{ github.event.inputs.project_title }}
        PAIRINGS_PATH: ${{ github.event.inputs.pairings_path }}
        PAIR_DATA_FILE: ${{ github.event.inputs.pair_data_file }}
      run: |
        python scripts/manage_mentorship_projects.py
